### PR TITLE
feat: Proposal for scripted approach to setup port forwardings.

### PR DESCRIPTION
**Pull request by danielburgmann**
`db-forward.sh` tested on Ubuntu 22.04 bash. Please review on Mac OS and let me know if this is usable.

### CODE REVIEW

**Comment by carhartl** [comment]
Just fyi, trying on macOS yields this:

```
❯ ./db-forward.sh
Usage: db-forward-up <config-file> <up|down>
.
Processes containing "port-forward" in their command line:
pgrep: illegal option -- -
usage: pgrep [-Lfilnoqvx] [-d delim] [-F pidfile] [-G gid]
             [-P ppid] [-U uid] [-g pgrp] [-t tty] [-u euid]
             pattern ...
.
```

**Comment by carhartl** [comment]
I think `pgrep -af ...` instead of `pgrep --list-full --full ...` is the portable variant..

**Review by carhartl — APPROVED** [review]
Very nice!

Few remarks/ideas:

- shellcheck reports a couple of issues that we could address
- Use shfmt for ensuring consistent shell script formatting
- Name the script `run.sh` so it's consistent with what is usually to be found in other repositories?

**Comment by carhartl** [comment]
Another thought I just had.. might conveniently setting up port-forwarding like this be a useful addition for `dsctl`? cc @kaibernhard

**Comment by danielburgmann** [comment]
* Recoded use of pgrep/pkill to ps -ef and awk as pgrep/pkill seem to have different argument implementations on macos and linux.
* Fixed everything but opionated info of shellcheck.
* Applied shfmt

**Comment by carhartl** [comment]
> Fixed everything but opionated info of shellcheck

How would I know what we agree with in shellcheck and what not, is it documented? What if I want to add automation? In my experience it makes our lives as developers easier if we simply accept what some tooling needs fixed instead of arguing about it, or maybe even try to configure it away. Another example is prettier — its formatting isn‘t always perfect, but I‘d prefer to accept it over configuring it, let alone manually editing code to my liking (we had discussions about that in the DS). This will ensure consistency (and by extension collective code ownership). Furthermore, what is (too) opinionated or what isn’t seems very subjective (opinionated, ha) by itself. My take, especially when it comes to pull requests, is: **don‘t discuss what you can automate away**. The tradeoff is that there might be things someone doesn’t agree with (which imo is outweighed by the benefits).

**Comment by carhartl** [comment]
PS: For me at least it‘s much easier not having to scan a tool‘s output and build up a mental model for what to ignore and what to take care of.

**Comment by carhartl** [comment]
Anyway, I had approved earlier, merge away!

**Comment by danielburgmann** [comment]
Shellcheck recommended to use pgrep/pkill but I only found reference information on the tools that seemed incompatible parameter flags between the macos and linux version. If time comes that I have a mac available, I will check the state.

**Pull request merged**
